apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crash-app
  template:
    metadata:
      labels:
        app: crash-app
    spec:
      containers:
      - name: crash-container
        image: nginx
        command: ["/bin/sh"]
        args: ["-c", "echo Crashing... && sleep 5 && exit 1"]
